<?php 
	//define('DBhost','localhost');
	//define('DBuser','koeyhni');
	//define('DBpass','ay2111!!');
	//define('DBname','koeyhni');
	define('DBhost','localhost');
	define('DBuser','ashram7');
	define('DBpass','ay2111!!');
	define('DBname','ashram7');
?>